<<<<<<< HEAD
=======
# This is a sample deployment manifest file for a simple web application.
>>>>>>> b17ef0d110626d6cc5b8a5c2c521b683fe1f4265
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app
  labels:
    app: go-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-web-app
  template:
    metadata:
      labels:
        app: go-web-app
    spec:
      containers:
      - name: go-web-app
<<<<<<< HEAD
        image: divyajp/go-web-app:v1.1
=======
        image: <docker-user-name>/go-web-app
>>>>>>> b17ef0d110626d6cc5b8a5c2c521b683fe1f4265
        ports:
        - containerPort: 8080